apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: sre-task-api
data:
  alert-rules.yml: |
    groups:
      - name: sre-task-api-alerts
        rules:
          - alert: SreTaskApiDown
            expr: up{job="sre-task-api"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "sre-task-api is down"
              description: "Prometheus cannot scrape sre-task-api for more than 1 minute."

          - alert: HighHttpErrorRate
            expr: |
              sum(rate(http_server_requests_seconds_count{status=~"5.."}[5m]))
              /
              sum(rate(http_server_requests_seconds_count[5m]))
              > 0.05
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High HTTP 5xx error rate"
              description: "More than 5% of requests are failing."

          - alert: HighP95Latency
            expr: |
              histogram_quantile(
                0.95,
                sum(rate(http_server_requests_seconds_bucket[5m])) by (le)
              ) > 0.5
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High p95 latency"
              description: "p95 latency is higher than 500ms."

          - alert: HighJvmMemoryUsage
            expr: |
              sum(jvm_memory_used_bytes{area="heap"})
              /
              sum(jvm_memory_max_bytes{area="heap"})
              > 0.80
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High JVM heap memory usage"
              description: "JVM heap usage is above 80%."