apiVersion: v1
kind: Service
metadata:
  name: sre-task-api
  namespace: sre-task-api
spec:
  type: NodePort
  selector:
    app: sre-task-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080