name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build and test
        run: ./gradlew clean build

      - name: Build Docker image
        run: docker build -t sre-task-api-app:ci .